### PR TITLE
Allow plugins to be used if the implement IPlugin directly rather than extending a base class

### PR DESCRIPTION
**Pull request by MattTrinder1**
#100  

Extended MockupSettings to accept a list of plugins which implement IPlugin directly - these are then loaded and registered directly one at a time rather than by loading the assembly.

Also extended MockupSettings to accept a metadata skeleton to allow it to be directly modified after being loaded.  This was necessary in order to be able to add the plugin registration steps for direct plugins as there is no where else to reference them from.  This will only be needed for internal testing of plugins in XRMMockup as in real life the steps would be read from the Dynamics metadata.

### CODE REVIEW

**Comment by MattTrinder1** [comment]
I've just stepped back to my real word project to give this a go, and have realised that listing 300 individual plugins is not really workable.  I'll have another think about how we can load them from an assembly.

**Comment by magesoe** [comment]
Load them like we load the code activities. We find the dll they're part of and find all code activities in that dll. So you only give a single plug-in for each dll you produce

**Comment by MattTrinder1** [comment]
> Load them like we load the code activities. We find the dll they're part of and find all code activities in that dll. So you only give a single plug-in for each dll you produce

Yep have gone for that approach - much better solution :-)

**Comment by MattTrinder1** [comment]
This should be reasonably complete now

**Comment by MattTrinder1** [comment]
This has been superceeded by #118

**Pull request closed without merging**
